import { ScrollView, Text } from "react-native";

const Scroll = () => {

    return(
        <ScrollView>
            <Text>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi sed neque quas repudiandae facere, magni quasi, maiores, natus exercitationem pariatur alias id soluta sint necessitatibus sequi delectus est temporibus deserunt?
                Hic nemo pariatur, possimus cumque, alias quibusdam iusto neque architecto voluptatibus exercitationem molestiae nobis, repudiandae necessitatibus facilis nihil esse dignissimos asperiores consequatur? Enim corporis, dicta optio illum accusantium adipisci maiores.
                Vero laborum distinctio earum architecto cumque vel, beatae nostrum numquam consequatur officiis sequi necessitatibus suscipit aliquam ipsum mollitia, sapiente dolores totam culpa possimus ab, aut fuga natus. Voluptatibus, voluptate quidem!
                Earum, consectetur alias id doloribus voluptate consequatur omnis recusandae atque accusamus deleniti unde est dolore esse ea doloremque distinctio ad laborum, ab quod consequuntur. Ducimus facilis quidem assumenda natus maiores.
                Soluta, nobis odio rerum maxime repellat cum sint eaque aut architecto enim. Voluptas recusandae sed quos iure, commodi corrupti illum deserunt reiciendis esse eligendi id earum eos alias repellendus nostrum.
                Et magni necessitatibus possimus quis suscipit molestiae est voluptas reiciendis facilis pariatur ex excepturi deserunt illum alias optio asperiores quidem accusantium porro nulla corrupti architecto blanditiis, nihil nobis consequatur! Accusantium?
                Delectus tenetur consectetur ea blanditiis officiis repudiandae provident eum iure omnis? Repudiandae maxime iste earum dolor provident tenetur modi fugiat ipsam animi distinctio? Quia non maxime nesciunt quasi asperiores aspernatur.
                Dolores dolorum fugiat asperiores non veritatis ad in hic magnam ipsa quis. Incidunt ullam error impedit tempora optio cum accusantium pariatur possimus sequi corporis, eligendi cumque temporibus laudantium? Esse, veniam?
                Est ad eaque cumque accusantium explicabo, iusto deserunt, a quas minima iste quo ea, unde veritatis distinctio in quisquam. Minima repellendus ipsum magni consectetur, excepturi soluta cumque id atque nam!
                Labore sequi repudiandae porro nihil enim, sit dolor at amet voluptates esse dignissimos quidem similique quam aut eveniet quis consectetur. Ipsam, quod optio! Fugiat sed a molestias tempore ex impedit.
                Sed inventore assumenda saepe consequatur! Ex mollitia expedita, cum dolore voluptatem cupiditate tenetur ipsam reprehenderit consequuntur itaque ab culpa quibusdam quo, adipisci a autem possimus ea quod id blanditiis eum.
                Est saepe quae aspernatur officiis. Culpa ad laboriosam hic, nisi odio sapiente fugiat molestiae dolorem distinctio consequatur minima voluptatibus voluptatum sunt minus perspiciatis rerum magnam. Repudiandae et ad commodi odit.
                Maxime sunt accusamus beatae aperiam pariatur tenetur dolor quas corrupti commodi aliquid, minus vitae sequi similique vero inventore? Vitae magni magnam doloribus blanditiis voluptate ipsam dolorem soluta ipsa? Placeat, adipisci!
                Esse vero laboriosam nisi optio quaerat atque totam hic non quam, explicabo sed assumenda cumque aliquam magni ipsam quisquam, quae placeat temporibus nam ad id, reiciendis amet? Officiis, illum nobis?
                Voluptatibus voluptas sunt officiis, impedit illum ullam hic beatae perspiciatis quas id ut, dicta architecto, autem magni alias! Placeat fuga repellat iure non, architecto quibusdam cumque pariatur exercitationem praesentium dolores.
                Ab natus voluptates alias, expedita vero nam officia illo delectus animi repellat accusamus quibusdam id, tenetur illum quasi quia sint sequi error omnis praesentium minus non, dolorem corporis magnam? Soluta.
                Fugiat, deserunt fuga! Assumenda veniam repellat aut dignissimos fuga facere a hic placeat temporibus, magnam facilis quis, quia consequatur excepturi suscipit ea est id quasi quo sint possimus, voluptate aliquid?
                Beatae debitis provident quis? Recusandae ex perspiciatis repudiandae? Delectus saepe provident harum architecto consequuntur eum reprehenderit sequi asperiores mollitia, amet consectetur quas quaerat? Distinctio sequi iure, voluptatum debitis magni ab.
                Eum velit non fuga corrupti nihil dolorum harum eligendi temporibus obcaecati. Inventore in incidunt eum sequi reprehenderit aspernatur minima ex dicta tenetur possimus laborum nam consequuntur, iste quia debitis hic!
                Sint dolorum iure dolorem assumenda ipsam illo, magnam rem omnis quo aut? Unde, a sequi molestias deleniti ut repellendus. Eveniet reiciendis modi optio blanditiis sapiente vel. Molestiae nesciunt inventore ab.
                Ducimus nemo dicta voluptatibus animi molestiae! Laborum aliquid ullam cupiditate unde tempora, dolorem quam. Incidunt, esse! Perspiciatis accusamus omnis voluptatum delectus temporibus perferendis ut, quisquam provident, id quae fugit quia?
                Nam aut fugit dolor hic quaerat porro quo? Dolores, fugit. Vitae architecto laudantium, ea explicabo quas temporibus. Unde nisi iure saepe perspiciatis et esse itaque quam eveniet, alias blanditiis laboriosam.
                Nisi illum dolorem qui maxime consectetur molestias modi iure est perferendis, possimus repellendus hic vel, facilis soluta? Est laboriosam sapiente at quo libero? Soluta consequatur dolores culpa. Iusto, amet dicta.
                Vel, exercitationem? Reprehenderit totam distinctio inventore voluptatibus amet illo non magni, atque, iste minus aperiam! Dolorem, impedit enim vero dignissimos, ipsa consectetur praesentium veritatis adipisci saepe repudiandae cumque nihil sunt!
                Voluptatem ut eaque soluta reiciendis? Voluptatem hic aspernatur, tempore facilis assumenda reprehenderit amet ut sequi, laudantium odit velit quasi nesciunt voluptas aliquam eos quia. Iusto nihil quibusdam explicabo eaque eos?
                Possimus incidunt quisquam qui reprehenderit iusto. Quaerat ullam quibusdam eligendi sequi explicabo deserunt minus voluptas, repudiandae ducimus animi unde repellendus voluptatibus facilis, dolorum cum quam quia obcaecati? Sed, rem nemo.
                Sit, maxime voluptatem. Cupiditate sunt facere labore odio blanditiis et optio veniam eos quaerat culpa. Nesciunt eos quam numquam nam non quas dignissimos maiores, fuga error earum magni iusto reprehenderit!
                Ad dolorem magni non, facilis nostrum, sunt, voluptate mollitia distinctio eveniet blanditiis rem suscipit quae voluptatem! Optio quas laudantium iusto minima nemo vitae eum laborum? Maiores alias suscipit nobis reiciendis!
                Quidem, id nihil ad nesciunt minima, similique, earum voluptas culpa temporibus officiis laudantium atque explicabo itaque quae nulla ullam. Fuga quibusdam expedita sed, magnam quas vitae dignissimos. Dicta, quidem beatae.
                Illo molestiae odio, quidem eveniet impedit obcaecati repellat, modi reprehenderit accusamus ad asperiores quae soluta maiores pariatur totam maxime aperiam consequatur aspernatur non nostrum provident neque recusandae repudiandae! Quis, numquam.
                Porro tempore earum ipsa. Aperiam ipsum quae adipisci consequuntur eveniet, hic totam deserunt ullam exercitationem, autem laudantium quaerat velit molestiae esse at praesentium tempore quas, soluta nesciunt unde. Temporibus, ullam!
                Libero reiciendis ea animi deleniti, suscipit labore modi rerum nostrum alias soluta error praesentium rem et sapiente explicabo repudiandae tempore architecto, laudantium laboriosam at pariatur ab voluptatum! Autem, voluptatum nesciunt.
                Ut cupiditate magni consequatur eos mollitia! Illo, quaerat ducimus cupiditate, ea nemo voluptate distinctio cumque autem magnam laborum laboriosam iusto, suscipit eos deleniti unde minima hic qui aliquid veniam numquam?
                Perferendis ipsa a placeat excepturi fugiat suscipit, veniam in quia, beatae delectus optio ea. Nemo soluta, suscipit quaerat eius eaque neque vero cumque fuga. Officia illum perferendis unde facilis nesciunt!
                Eius facilis mollitia aut, distinctio fuga quae. Nemo sit porro mollitia. Facere illo sequi fuga exercitationem et at nihil? Harum quasi excepturi rerum fuga magnam voluptas facere delectus ipsam blanditiis!
                Aliquam, reiciendis eius accusamus quas nisi beatae quos veniam voluptatibus, velit laudantium dolorem exercitationem at reprehenderit blanditiis vero magnam, aliquid ut sed repellat. Iure ipsam, totam ducimus rerum velit numquam?
                Illum id iusto et! Neque magni perferendis corporis quis explicabo veniam voluptatem delectus sed nostrum assumenda nihil, ipsam soluta temporibus nobis sapiente odio mollitia deleniti repudiandae impedit tempora placeat eligendi?
                Quod tempora eum cumque earum perspiciatis animi assumenda incidunt quibusdam eos vitae, reprehenderit quis pariatur aperiam! Quis vel cum, quam pariatur repudiandae cumque est architecto facere, rerum dicta quasi beatae.
                Quo dolores, corporis ratione nulla ab dignissimos possimus nihil sit obcaecati ex, temporibus, alias earum incidunt vero consequatur corrupti voluptas cupiditate hic vel facilis accusantium voluptatem repellendus praesentium minima! Ad!
                Laboriosam quisquam natus nisi, libero quam sed voluptatibus distinctio, cum minima totam blanditiis magni eum, vero voluptas incidunt maxime possimus ex! Voluptas voluptatibus aperiam nam vero enim saepe facilis deserunt.
                Harum id ipsum perspiciatis, est dolorem, eum, quaerat corporis dolore reprehenderit doloremque eaque laborum ducimus eius saepe nostrum quos. Alias, sint? Eius possimus blanditiis tempora dolorum voluptas delectus fuga. Qui!
                Saepe exercitationem quidem temporibus dolore, alias, quas reprehenderit doloremque itaque vero, nam eos blanditiis ducimus inventore molestiae. Eligendi, placeat. Corrupti natus, hic doloribus assumenda beatae similique nemo rem fugiat laudantium?
                Corrupti fugiat dolorum quasi omnis dignissimos voluptas quo, vitae aliquid alias. Tenetur enim velit molestias? Maxime impedit cupiditate ipsa provident iusto voluptas, dolor aliquid velit, expedita, quis maiores eum commodi?
                Architecto aliquam consequuntur odit dolore vitae eligendi neque ipsam repellat sit error placeat, corporis corrupti modi ea vero doloribus qui iste distinctio sed magni quod beatae adipisci nisi! Illum, nobis.
                Porro reprehenderit laborum fugiat aliquam magni similique quae sequi vero! Voluptatum, laudantium commodi sapiente explicabo unde, voluptas ipsa vel consequatur molestiae excepturi suscipit, id voluptates deserunt adipisci fugit illum labore?
                Autem iste minus corrupti perferendis, soluta doloribus veniam. Nisi, eveniet dolorum? Rem nobis cupiditate quos laboriosam nesciunt vel dolorem nemo quidem consequatur sequi. Explicabo modi nesciunt impedit perspiciatis sapiente earum.
                Molestiae, itaque perspiciatis! Illo inventore explicabo adipisci excepturi delectus porro qui obcaecati officiis, possimus reprehenderit asperiores laudantium, eveniet at veniam quam fugiat amet neque sapiente totam aliquid corrupti, ut commodi?
                Possimus ullam nobis beatae quod dolores atque corporis dicta? Labore quaerat illum nemo sit tenetur, corporis in quas minus architecto enim consequuntur est inventore? Amet atque error sint commodi quod.
                Saepe quod rem obcaecati dicta. Quisquam fugit aliquam illum ad reprehenderit totam, magnam, in fuga quibusdam impedit quas omnis illo iure architecto. Laboriosam vero maxime, quam quasi odit ea. Ex.
                Provident porro consectetur reprehenderit ratione quis quam doloribus error est distinctio incidunt, praesentium dolore? Blanditiis repudiandae, laudantium dignissimos rem, distinctio, sed quisquam quidem illum dolorum atque repellat commodi minima quibusdam.
                Dolorem rerum eligendi explicabo nobis enim voluptatibus deleniti eum tempora minus, esse cumque velit et non quos excepturi quidem hic minima aliquid, ipsum obcaecati nisi at nostrum. Excepturi, obcaecati ad?
                Obcaecati inventore quam veniam? Fuga pariatur modi veritatis. Voluptatem laudantium eligendi mollitia cupiditate obcaecati incidunt, eveniet ipsam blanditiis amet aliquid! Dolores autem placeat sit, est et asperiores id natus sunt?
                Autem aut quia velit corporis accusamus, suscipit vero neque, temporibus deserunt voluptates non provident voluptas repellat est! Ullam, nam pariatur! Iste, nam fuga? Veniam voluptatibus harum corporis. Eos, in ad.
                Repellat culpa impedit exercitationem officia quisquam molestias non aut at. Veniam facilis tenetur officiis voluptatem culpa minima minus voluptatibus aspernatur. Iusto sint ad delectus quae hic odio laboriosam quasi corporis?
                Fuga corporis odit, at porro exercitationem, nostrum impedit ipsa, adipisci consectetur ullam explicabo. Minima qui impedit dignissimos, possimus, quaerat deleniti saepe repudiandae ab deserunt consequatur iusto, est sunt? Nesciunt, voluptatum.
                Id eum dolores, rerum obcaecati praesentium reiciendis culpa dolor sed aspernatur omnis deserunt repudiandae nemo asperiores officia, corporis modi. Quaerat id aspernatur odio. Possimus, esse eius dicta minus quia culpa!
                Laudantium distinctio cum veniam recusandae magni accusantium obcaecati autem magnam tempora nam quibusdam deleniti reiciendis, harum officiis quasi possimus! Delectus provident accusantium, aut aperiam cumque omnis tenetur doloremque praesentium blanditiis!
                Enim, odit culpa perspiciatis nisi doloribus illo fuga tempore ab fugit minus cumque dolorem quae. Incidunt ullam earum harum et maiores aliquam, deleniti quis, excepturi facilis tenetur, ab non aliquid.
                Fugiat a libero deserunt nemo! Explicabo modi iste exercitationem commodi nemo culpa vero, doloribus consequuntur voluptatem corporis ab laborum porro vel iusto quibusdam eaque quo tenetur eligendi. Ea, ratione rerum.
                Optio consectetur amet unde velit facilis, iure architecto dolorem. Corporis veniam eligendi dignissimos praesentium quos nemo dicta natus eveniet eum ullam est, facilis eius reiciendis nam rem, corrupti unde commodi?
                Fuga, enim, sint debitis distinctio quos voluptas nam modi necessitatibus itaque dolores qui? Voluptates architecto nemo dicta cum voluptate debitis explicabo porro numquam, perferendis odio illo expedita quis eligendi excepturi.
                Excepturi tempora vitae animi, voluptatibus aut eius ullam in laborum incidunt impedit culpa quod mollitia, delectus nesciunt, veniam distinctio saepe earum dolorum recusandae deleniti atque doloribus unde? Quod, eligendi excepturi.
                Nobis error, earum dignissimos mollitia unde a explicabo optio, dolores ipsum iure placeat eligendi natus amet quisquam quis consequuntur odit. Nobis, aliquid. Similique sequi porro quis, cumque quia itaque necessitatibus!
                Laborum autem, velit placeat labore vero tenetur saepe nobis quidem minima omnis ipsa quaerat laudantium, delectus eligendi debitis consequatur alias sed unde adipisci corrupti accusantium eveniet fuga at nihil. Placeat!
                Praesentium ipsum, accusantium, hic vero sequi consequuntur quidem autem, consequatur totam molestias sunt amet facere inventore quaerat iusto quis fugiat error ducimus dolore. At in nesciunt porro omnis ipsam odio!
                Deleniti quibusdam sapiente facilis veritatis. Rem iure, rerum excepturi recusandae tempora facere hic, officiis nisi ullam veritatis deserunt molestias vero. Adipisci maiores facere aliquam pariatur nobis fuga iure neque dignissimos.
                Iusto rerum excepturi omnis possimus. Quam, ullam delectus! Eaque, culpa sapiente. Natus accusamus explicabo voluptas eum vitae ducimus eligendi impedit amet cumque consectetur debitis, quas laborum, autem eaque magnam exercitationem?
                Vero doloribus, saepe doloremque fugit in non sed consequatur veritatis quis optio ducimus, recusandae placeat atque commodi repudiandae laudantium rem laborum cupiditate autem quidem ipsa nemo distinctio! Ipsum, nulla placeat.
                Assumenda vitae quae nostrum eveniet quam, accusamus esse expedita similique dicta, a impedit ut maxime tempora! Asperiores veritatis quos quae, exercitationem expedita obcaecati nobis, ab deleniti, accusantium fuga unde beatae!
                Beatae iusto, modi dolorum eius ullam, voluptates magni est illum sit, possimus fuga pariatur? Neque temporibus dignissimos ea accusantium molestiae asperiores dolorum, reprehenderit at omnis totam odio, consequuntur nobis libero.
                Repudiandae explicabo tempore itaque distinctio exercitationem nemo ea atque voluptates numquam maxime quidem, officia nobis tempora fugiat mollitia laboriosam nostrum non amet ex unde ipsam voluptatum? Repellendus tempore aut veniam?
                Veniam voluptate labore, magni sed veritatis laborum inventore, a facilis maxime fuga impedit fugit? Qui itaque ipsam ipsum quia quidem atque fugiat natus dolorum error, soluta nostrum provident mollitia suscipit.
                Atque dolores repudiandae nostrum suscipit sequi quae veniam adipisci. Dolore adipisci consectetur voluptate libero eos ut facilis doloremque delectus perspiciatis deleniti? Adipisci tenetur ad quam numquam delectus sed sunt voluptatum.
                Eaque nobis sequi alias ratione sapiente eius amet optio atque nam, similique totam quaerat quidem, repudiandae esse beatae est delectus possimus cum quibusdam! Nam consequatur perferendis dicta repudiandae nisi qui!
                Ullam quis ipsam quas delectus quibusdam ex temporibus sit! Cumque magnam laudantium cupiditate, quam libero labore ullam, ratione veniam ipsa deserunt, eveniet excepturi voluptatibus qui ipsam sunt corrupti! Ullam, reprehenderit!
                Recusandae similique nulla fugiat provident voluptatum aut ad cupiditate cum, veritatis, illum dolorem sequi modi ab minus autem! Laboriosam veritatis harum sunt itaque repudiandae maiores delectus fugiat? Accusamus, excepturi quidem.
                Culpa, totam? Atque consequatur dolorem ea. Modi deserunt soluta quia accusamus quo exercitationem facilis? Iusto eum rerum vero fuga, illum autem voluptatum nam nisi est expedita velit reiciendis dolore voluptatem?
                Fuga amet pariatur quasi ex quos quam expedita quisquam excepturi officia perspiciatis ipsum, deserunt, porro enim sunt delectus accusamus esse incidunt tempore doloremque. Hic ipsum blanditiis et a culpa enim!
                Ipsum veniam dicta accusantium ratione sapiente iure a repudiandae labore! Porro sint tempora debitis impedit quaerat dignissimos soluta, explicabo ea similique quas error excepturi maxime deleniti nisi, ut nesciunt alias?
                Autem optio doloribus, ex odit, voluptas tempora voluptate dignissimos impedit omnis, corporis hic eum? Nobis eos sapiente delectus velit architecto consectetur quam voluptate facilis rerum porro. Facere tenetur laudantium magnam!
                Suscipit vel, quis veniam eum harum ad sed provident, cupiditate sint reprehenderit dolorum ullam beatae, itaque fugiat amet aperiam quibusdam adipisci exercitationem dolore error laboriosam similique repellendus mollitia laborum. Magni!
                Dolorem quisquam ab voluptates neque similique incidunt delectus est beatae, suscipit, magni placeat deserunt, omnis sapiente porro odit debitis expedita ea dicta ipsam aliquam cumque. Ab dolorum non laudantium distinctio?
                Reiciendis facere corrupti praesentium vitae, excepturi unde eaque optio nihil nostrum ipsam officia quae expedita officiis in tempora voluptates ratione aut aliquam fuga ducimus odio. Laudantium error optio nisi quaerat!
                Hic reiciendis debitis reprehenderit, totam assumenda quibusdam distinctio sed ab ratione suscipit ea, facilis aspernatur sint eum nam corrupti odit, consequuntur commodi neque temporibus natus? Distinctio sunt dicta cupiditate quaerat.
                Culpa, quod hic. Deserunt, recusandae minus. Tenetur sed iste temporibus itaque molestiae laborum, autem doloremque eos, aperiam accusamus, est illo sit. Dolorum in placeat rem optio iste, animi cum provident?
                Earum magnam nam nesciunt voluptatum veniam eius ab soluta totam, aliquam excepturi, voluptas sequi debitis vitae molestias laudantium molestiae quia harum maxime. Cupiditate fugiat nisi est itaque? Aliquam, natus magni.
                Neque porro ad esse, rerum temporibus eius dicta cumque dolorem sit incidunt explicabo. Animi quidem molestiae, soluta cum rem vitae maxime libero voluptatem rerum veniam fugit qui debitis! Tempora, nisi.
                Eligendi hic totam consequatur debitis fugit, nobis saepe aliquam aut nisi id ex, similique ut quos amet quidem natus doloribus voluptatibus vel eos esse iusto veniam quasi? Assumenda, reprehenderit laboriosam.
                Expedita ipsum consectetur necessitatibus modi facere quam nisi aut, iusto rem soluta quidem magnam quisquam, suscipit at culpa a quod dignissimos saepe provident itaque velit, placeat incidunt odio. Blanditiis, vitae!
                Sequi harum ad ut laborum aspernatur optio magni totam minima et, accusamus corrupti quibusdam aut perspiciatis illo ipsum unde eligendi libero sit sint vero nostrum, vitae voluptatum. Possimus, minus delectus.
                Placeat quibusdam ratione ipsum quis ullam eum id odio. Laborum, velit perspiciatis! Cumque, ullam. Ea dolore tempora dolores tenetur ex expedita incidunt explicabo, omnis distinctio quo nostrum aperiam numquam deserunt.
                Commodi voluptatibus soluta dolorum cum ipsum mollitia, laboriosam eius quae nisi quas earum, eaque quis voluptates debitis velit error obcaecati, harum fugiat. Voluptate quaerat cupiditate hic? Voluptatum amet a recusandae!
                Nam animi eius praesentium quod reprehenderit voluptatem repudiandae eum nulla voluptas cumque et quo quasi nisi assumenda, laborum eaque mollitia ad quos! Id eius expedita repellendus nobis. Cumque, nihil fugiat!
                Cum mollitia odit harum ducimus animi nesciunt velit voluptatem, sint accusantium dolore. Quo, ad saepe. Minus nesciunt in, accusamus voluptate officia quis dicta quaerat iure laboriosam tempora alias voluptatibus unde.
                Facere quia suscipit qui facilis ea maiores magni dolores. Numquam similique, minima quibusdam laboriosam eveniet rem placeat quos nulla beatae expedita dolorem! Fugiat, blanditiis nisi minus explicabo repudiandae quaerat consequuntur.
                Corrupti obcaecati impedit eius, laboriosam molestiae recusandae suscipit explicabo, laudantium sed officia rerum ipsam, fuga sapiente. Consequuntur similique quia saepe blanditiis doloremque quo est. Hic labore neque eius vitae ex!
                Asperiores aut officia dolores delectus quam fugit facere unde ad corrupti laborum corporis, dolor quisquam laudantium quod atque, nisi quasi ipsam! Voluptatibus, amet provident velit tenetur adipisci accusantium. Quisquam, expedita!
                Qui sequi quis quibusdam aliquam inventore esse magni ut repellat cumque a quas saepe eveniet ab illum ratione eius, sint tenetur ducimus itaque quaerat maiores mollitia molestias. Commodi, nam expedita?
                Officia eligendi dolorem atque temporibus nulla, doloribus voluptas et perferendis cupiditate sunt nesciunt dolore harum itaque voluptates, deleniti quos est quod. Non ratione autem consequatur qui natus recusandae suscipit sunt?
                Vitae aperiam exercitationem voluptates quidem ipsam beatae tempore ducimus temporibus. Sint tenetur atque voluptatum explicabo sequi, tempora dignissimos temporibus quos odit illo! Totam, odio ut ab pariatur asperiores cum eos?
            </Text>
        </ScrollView>
    )

}

export default Scroll;